// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class Carts
    {
        public Carts()
        {
            CartItems = new HashSet<CartItems>();
        }

        public int Id { get; set; }
        public string MemberAccount { get; set; }

        public virtual Members MemberAccountNavigation { get; set; }
        public virtual ICollection<CartItems> CartItems { get; set; }
    }
}