// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class Orders
    {
        public Orders()
        {
            OrderItems = new HashSet<OrderItems>();
        }

        public int Id { get; set; }
        public int MemberId { get; set; }
        public int Total { get; set; }
        public DateTime CreatedTime { get; set; }
        /// <summary>
        /// 1=訂單成立, 2=已結案, -1=已退訂
        /// </summary>
        public int Status { get; set; }
        /// <summary>
        /// 客戶是否提出退訂要求
        /// </summary>
        public bool RequestRefund { get; set; }
        public DateTime? RequestRefundTime { get; set; }
        public string Receiver { get; set; }
        public string Address { get; set; }
        public string CellPhone { get; set; }

        public virtual Members Member { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}